### ISSUE TITLE
Callback to continue execution after update check

### ISSUE THREAD

**Issue by rynkowsg** [motorro/AppUpdateWrapper#9]
Hi, It is quite a nice library. Thanks for making it.

I've got a question: Is it possible to use this library as a "check for an update & if available update" step in SplashScreen. So when there is no update, just continue the app, but if there is an update, install it.

Cheero

**Comment by motorro** [comment]
Hi @rynkowsg 
Sorry for the late reply!
Missed your question - notifications somehow don't work for me 😠 

If I get you right you may use these callbacks in your splash:
* [updateChecking](https://github.com/motorro/AppUpdateWrapper#updatechecking-optional) - to display some spinner
* [updateComplete](https://github.com/motorro/AppUpdateWrapper#updatecomplete-optional) - called if there is no update or user cancels google-play update consent
 
Plus some custom processing in `onActivityResult` (below)

Here is what happens with different flexible flows:

### Checking, update NOT available
1) Launch flexible update
2) Optionally display spinner on callback
3) No update, and `updateComplete` gets called. You proceed to next activity.

### Checking, update available, user cancels
1) Launch flexible update
2) Optionally display spinner on callback
3) Play core consent appears
4) User cancels
3) `updateComplete` gets called and you proceed to next activity.

### Checking, update available, user confirms
1) Launch flexible update
2) Optionally display spinner on callback
3) Play core consent appears
4) User confirms. Here you should process `onActivityResult` like explained [here](https://github.com/motorro/AppUpdateWrapper/issues/6#issuecomment-544518226) as there is no view update on download start (may be it is worth implementing though).
5) Proceed to next activity as download continues in background. Be sure to start flexible flow there too as it will catch up with update manager current state and prompt you to install.

**Comment by motorro** [comment]
You may also try IMMEDIATE update as a blocking UI for update but you need either:
1) To implement some method on your backend that mandatory update is needed. The problem here the play store cache may not be of latest version at the moment and IMMEDIATE update will fail. 
2) Check update with update manager yourself, then start immediate flow.

The IMMEDIATE update in this library is designed more like mandatory one. So if the update is not available or cancelled you'll get [updateFailed](https://github.com/motorro/AppUpdateWrapper#updatefailed-mandatory). If it is OK for you - than it is also a way to go
[Here](https://github.com/motorro/AppUpdateWrapper/blob/a77d513da6fc2d943bcc1e3e1b06672a438ddf93/appupdatewrapper/src/main/java/com/motorro/appupdatewrapper/ImmediateUpdateState.kt#L142) is how the update info is processed for immediate flow

**Comment by motorro** [comment]
@rynkowsg
Please check the [upgradeDownloadStarts](https://github.com/motorro/AppUpdateWrapper#updateDownloadStarts-optional) callback added to [v1.5.0](https://github.com/motorro/AppUpdateWrapper/releases/tag/v1.5.0)
